import Footer from "@/components/Footer";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Haider Holding Autover",
  description: "Generated by Firoz Miya",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="appContainer">
          <div className="navWrapper">
            <Nav />
          </div>
          <div className="mainWrapper">{children}</div>
          <footer className="footerWrapper">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
